### PR TITLE
Update pico-8.md

### PR DESCRIPTION
**Pull request by JKxZ**
Updated the setup instructions with a note regarding necessary file/folder permissions.

Added an additional check step to ensure Pico-8 can be launched successfully after setup. This step also creates the carts folder. Directed users to then place game files into this directory.

Fixed several spelling errors.

### CODE REVIEW

**Review by anthonycaccese — COMMENTED** [review]
thank you for this!  this looks good.

One note though is that I think we should keep the detail about the ability to add carts directly into the roms/pico-8 directory.   That is not impacted by permissions from my testing and allows users a quick way to launch games directly that they are interested in without needing to go an extra level deeper into the filesystem.  

Please let me know what you think.

**Comment by anthonycaccese** [comment]
Thinking something like this...

Change:
"On launch Pico-8 will create the carts directory. You can then copy .png or .p8 files into this directory."

To:
On launch Pico-8 will create a carts directory in `/roms/pico-8/carts`.  If you add your .png/.p8 files directly to that folder then they will show up in Splore under the file management section.  You can also access them in EmulationStation by navigating to the carts folder that displays in the pico-8 gamelist.   Additional details about the options for launching games can be seen below.

**Comment by JKxZ** [comment]
Change makes sense to me.

**Comment by anthonycaccese** [comment]
looking at this again this morning i wonder if we need the details about permissions any longer following this change: https://github.com/JustEnoughLinuxOS/distribution/blob/92410034608974cce3c4613f5c20d3cd0a9c2063/packages/emulators/standalone/pico-8/sources/start_pico8.sh#L46

I'll test with a fresh SD card in the next few days to check.

**Comment by anthonycaccese** [comment]
nice, thats what i figured.  will check, confirm and update in a few days.

**Comment by anthonycaccese** [comment]
confirmed, permissions are set automatically now - no longer a need for a user to set them by hand

**Pull request merged**
